# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/awesome-resources',
                'doc_host': 'https://pythonspaces.github.io',
                'git_url': 'https://github.com/pythonspaces/awesome-resources',
                'lib_path': 'awesome_resources'},
  'syms': {'awesome_resources.core': {'awesome_resources.core.foo': ('core.html#foo', 'awesome_resources/core.py')}}}